mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
unified-delay: true

proxies:
  - name: "US-Hy2"
    type: hysteria2
    server: 73.210.24.148
    port: 8443
    password: qTkQOlDvzBVTKxfuGbQN04WZRf8rH+bqB8RVPSIoPQk=
    sni: apple.com
    skip-cert-verify: true
    up: "200 mbps"
    down: "500 mbps"

  - name: "US-VLESS"
    type: vless
    server: 73.210.24.148
    port: 443
    uuid: 982a3bb1-2594-4cc1-a4cb-5479b85d99a4
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.microsoft.com
    client-fingerprint: chrome
    reality-opts:
      public-key: 4V0ckEvYE-R614M-ke9N4NqgR9ZzMqOktGV-H6Qqzi8
      short-id: abcd1234

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "US-Hy2"
      - "US-VLESS"
      - DIRECT

rules:
  - DOMAIN-SUFFIX,lakespa.us,DIRECT
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-KEYWORD,baidu,DIRECT
  - DOMAIN-KEYWORD,taobao,DIRECT
  - DOMAIN-KEYWORD,alibaba,DIRECT
  - DOMAIN-KEYWORD,tencent,DIRECT
  - DOMAIN-KEYWORD,bilibili,DIRECT
  - DOMAIN-KEYWORD,163,DIRECT
  - DOMAIN-KEYWORD,netease,DIRECT
  - DOMAIN-KEYWORD,jd.com,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
