mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
unified-delay: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - "*.localhost"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN

proxies:
  - name: "US-Home"
    type: vless
    server: vpn.lakespa.us
    port: 443
    uuid: 982a3bb1-2594-4cc1-a4cb-5479b85d99a4
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.microsoft.com
    client-fingerprint: chrome
    reality-opts:
      public-key: 4V0ckEvYE-R614M-ke9N4NqgR9ZzMqOktGV-H6Qqzi8
      short-id: abcd1234

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "US-Home"
      - DIRECT

rules:
  - DOMAIN-SUFFIX,lakespa.us,DIRECT
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-KEYWORD,baidu,DIRECT
  - DOMAIN-KEYWORD,taobao,DIRECT
  - DOMAIN-KEYWORD,alibaba,DIRECT
  - DOMAIN-KEYWORD,tencent,DIRECT
  - DOMAIN-KEYWORD,bilibili,DIRECT
  - DOMAIN-KEYWORD,163,DIRECT
  - DOMAIN-KEYWORD,netease,DIRECT
  - DOMAIN-KEYWORD,jd.com,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
